name: 'AWS Marketplace | ECR Image Mirror'
inputs:
  from:
    description: "The name and version of the docker image. For example: camunda/zeebe:8.2.7"
    type: string
  to:
    description: "The name and version of the destination to push the image to. For example: 709825985650.dkr.ecr.us-east-1.amazonaws.com/camunda/zeebe:8.2.7"
    type: string
runs:
  using: "composite"
  steps:
    - name: Pull the docker image
      run: docker pull ${{ inputs.from }}
      shell: bash

    - name: Tag the docker image
      run: docker tag ${{ inputs.from }} ${{ inputs.to }}
      shell: bash

    - name: Push the docker image
      run: docker push ${{ inputs.to }}
      shell: bash
