name: Install Playwright
description: Install Playwright and its dependencies

inputs:
  working-directory:
    description: Path of Playwright config and tests
  browsers:
    description: Playwright browsers to install
    default: chromium

runs:
  using: composite
  steps:
    - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      id: npm-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Check cache hit
      shell: bash
      run: |
        echo "Cache hit: ${{ steps.npm-cache.outputs.cache-hit }}"

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm ci

    - name: Install Playwright browsers
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npx playwright install --with-deps ${{ inputs.browsers }}
