name: Install Playwright
description: Install Playwright and its dependencies

inputs:
  working-directory:
    description: Path of Playwright config and tests
  browsers:
    description: Playwright browsers to install
    default: chromium

runs:
  using: composite
  steps:
    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
      id: npm-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Check cache hit
      shell: bash
      run: |
        echo "Cache hit: ${{ steps.npm-cache.outputs.cache-hit }}"

    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm ci

    - name: Install Playwright browsers
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npx playwright install --with-deps ${{ inputs.browsers }}
