name: Install Playwright
description: Install Playwright and its dependencies

inputs:
  working-directory:
    description: Path of Playwright config and tests

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
      with:
        node-version: 24

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm ci

    - name: Install Playwright browsers
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npx playwright install --with-deps chromium
