name: Install Playwright
description: Install Playwright and its dependencies

inputs:
  working-directory:
    description: Path of Playwright config and tests
  browsers:
    description: Playwright browsers to install
    default: chromium

runs:
  using: composite
  steps:
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
      id: npm-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Check cache hit
      shell: bash
      run: |
        echo "Cache hit: ${{ steps.npm-cache.outputs.cache-hit }}"

    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: 24

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm ci

    - name: Install Playwright browsers
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npx playwright install --with-deps ${{ inputs.browsers }}
