name: Install Playwright
description: Install Playwright and its dependencies

inputs:
  working-directory:
    description: Path of Playwright config and tests

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 24

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm ci
