camunda:
  console:
    customerId: "camunda-platform-test"
    installationId: "camunda-platform-test"
    telemetry: "disabled"
    managed:
      method: "plain"
      releases:
        - name: "camunda-platform-test"
          namespace: "camunda-platform-test"
          version: "8.8.0-SNAPSHOT"
          tags:
            - "test"
            - "local"
          components:
            - name: "Zeebe Gateway"
              id: "zeebeGateway"
              version: "8.8.0-SNAPSHOT"
              urls:
                grpc: "grpc://localhost:26500"
                http: "http://localhost:8080"
              readiness: "http://orchestration-cluster:9600/actuator/health/readiness"
              metrics: "http://orchestration-cluster:9600/actuator/prometheus"
            - name: "Operate"
              id: "operate"
              version: "8.8.0-SNAPSHOT"
              url: "http://localhost:8080/operate"
              readiness: "http://orchestration-cluster:9600/actuator/health/readiness"
              metrics: "http://orchestration-cluster:9600/actuator/prometheus"
            - name: "Tasklist"
              id: "tasklist"
              version: "8.8.0-SNAPSHOT"
              url: "http://localhost:8080/tasklist"
              readiness: "http://orchestration-cluster:9600/actuator/health/readiness"
              metrics: "http://orchestration-cluster:9600/actuator/prometheus"
            - name: "Identity"
              id: "identity"
              version: "8.8.0-SNAPSHOT"
              url: "http://localhost:8081"
              readiness: "http://management-identity:8082/actuator/health"
              metrics: "http://management-identity:8082/actuator/prometheus"
            - name: "Connectors"
              id: "connectors"
              version: "8.8.0-alpha8"
              url: "http://localhost:8086"
              readiness: "http://connectors:8080/actuator/health/readiness"
              metrics: "http://connectors:8080/actuator/prometheus"