name: "AWS Marketplace | Mirror: Elasticsearch"

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "The image tag for the elasticsearch image"
        required: true
        # renovate: datasource=docker depName=bitnami/elasticsearch
        default: 8.17.0
  push:
    branches:
      - main
    paths:
      - '.github/workflows/aws-marketplace-elasticsearch.yaml'

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/aws-marketplace-ecr-login
        with:
          aws-role-arn: "arn:aws:iam::${{ secrets.DISTRO_CI_AWS_MPLACE_AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction"
          aws-region: "us-east-1"

      - name: mirror elasticsearch image
        uses: ./.github/actions/aws-marketplace-ecr-mirror
        with:
          from: bitnami/elasticsearch:${{ inputs.imageTag }}
          to: ${{ env.MARKETPLACE_BASE_URL }}/camunda/camunda8/elasticsearch:${{ inputs.imageTag }}
