name: "AWS Marketplace | Build: license-manager"

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "The image tag for license-manager"
        required: true
        default: 0.0.1

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/aws-marketplace-ecr-login
        with:
          aws-role-arn: "arn:aws:iam::${{ secrets.DISTRO_CI_AWS_MPLACE_AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction"
          aws-region: "us-east-1"

      - name: Build the docker image
        run: docker build -f aws-marketplace/license-manager/Dockerfile -t $MARKETPLACE_BASE_URL/camunda/camunda8/license-manager:$IMAGE_TAG license-manager
        env:
          IMAGE_TAG: ${{ inputs.imageTag }}
          MARKETPLACE_BASE_URL: ${{ secrets.DISTRO_CI_AWS_MPLACE_BASE_URL }}

      - name: Push the docker image
        run: docker push $MARKETPLACE_BASE_URL/camunda/camunda8/license-manager:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ inputs.imageTag }}
          MARKETPLACE_BASE_URL: ${{ secrets.DISTRO_CI_AWS_MPLACE_BASE_URL }}
