name: "AWS Marketplace | Mirror: Optimize"

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "The image tag for the optimize image"
        required: true
        # renovate: datasource=docker depName=camunda/optimize
        default: 8.6.1
  push:
    branches:
      - main
    paths:
      - '.github/workflows/aws-marketplace-optimize.yaml'

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/aws_marketplace_ecr_login
        with:
          aws-role-arn: "arn:aws:iam::${{ secrets.DISTRO_CI_AWS_MPLACE_AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction"
          aws-region: "us-east-1"
          
      - name: Pull the docker image
        run: docker pull camunda/optimize:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ inputs.imageTag }}

      - name: Tag the docker image
        run: docker tag camunda/optimize:$IMAGE_TAG $MARKETPLACE_BASE_URL/camunda/camunda8/optimize:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ inputs.imageTag }}

      - name: Push the docker image
        run: docker push $MARKETPLACE_BASE_URL/camunda/camunda8/optimize:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ inputs.imageTag }}
