name: Renovatebot | Config Check

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/renovatebot-config-check.yaml'
      - '.github/renovate.json5'
      - '.github/config/renovatebot/**'
  pull_request:
    paths:
      - '.github/workflows/renovatebot-config-check.yaml'
      - '.github/renovate.json5'
      - '.github/config/renovatebot/**'
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  check:
    name: Check renovate config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Validate renovate config
      uses: docker://renovate/renovate
      with:
        entrypoint: bash
        args: -c "renovate-config-validator .github/renovate.json5 .github/config/renovatebot/*"
